use_frameworks!

target 'HPCustomAlertController_Example' do
#  pod 'HCPCustomAlertController', :path => '../'

  pod 'SnapkitArrayExtention'
  target 'HPCustomAlertController_Tests' do
    inherit! :search_paths
  end
end
